name: Deploy Python Microservice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t rajataha/fyp-python-microservice .
      - name: Publish Image to Docker Hub
        run: docker push rajataha/fyp-python-microservice:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull rajataha/fyp-python-microservice:latest
      - name: Delete old container
        run: docker rm -f fyp-python-microservice-container || true
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name fyp-python-microservice-container -e PORT='${{ secrets.PORT }}' -e HOST='${{ secrets.HOST }}' -e SERVER_URL='${{ secrets.SERVER_URL }}' rajataha/fyp-python-microservice
